export const GET_USERS_BEGIN = "GET_USERS_BEGIN";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_ERROR = "GET_USERS_ERROR";

export const GET_CURRENT_USER_BEGIN = "GET_CURRENT_USER_BEGIN"
export const GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS"
export const GET_CURRENT_USER_ERROR = "GET_CURRENT_USER_ERROR"

export const GET_USER_BEGIN = "GET_USER_BEGIN";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_ERROR = "GET_USER_ERROR";

export const HANDLE_CHANGE = "HANDLE_CHANGE";

export const CLEAR_SEARCH = "CLEAR_SEARCH";

export const SET_INITIAL_STATE = "SET_INITIAL_STATE";

export const FRIEND_REQUESTS_BEGIN = "FRIEND_REQUESTS_BEGIN";
export const FRIEND_REQUESTS_SUCCESS = "FRIEND_REQUESTS_SUCCESS";
export const FRIEND_REQUESTS_ERROR = "FRIEND_REQUESTS_ERROR";

export const UPLOAD_BEGIN = "UPLOAD_BEGIN";
export const UPLOAD_SUCCESS = "UPLOAD_SUCCESS";
export const UPLOAD_ERROR = "UPLOAD_ERROR";