export const GET_POSTS_BEGIN = "GET_POSTS_BEGIN";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POSTS_ERROR = "GET_POSTS_ERROR";

export const GET_USER_POSTS_BEGIN = "GET_USER_POSTS_BEGIN";
export const GET_USER_POSTS_SUCCESS = "GET_USER_POSTS_SUCCESS";
export const GET_USER_POSTS_ERROR = "GET_USER_POSTS_ERROR";

export const CREATE_POST_BEGIN = "CREATE_POST_BEGIN";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_ERROR = "CREATE_POST_ERROR";

export const CHANGE_PAGE = "CHANGE_PAGE";

export const CHANGE_USER_PAGE = "CHANGE_USER_PAGE";

export const LIKE_POST = "LIKE_POST";

export const SET_INITIAL_STATE = "SET_INITIAL_STATE";

export const SET_POST = "SET_POST";

export const CREATE_COMMENT_BEGIN = "CREATE_COMMENT_BEGIN";
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
export const CREATE_COMMENT_ERROR = "CREATE_COMMENT_ERROR";

export const DELETE_COMMENT_BEGIN = "DELETE_COMMENT_BEGIN";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_ERROR = "DELETE_COMMENT_ERROR";

export const RESET_COMMENT_EDIT_MODE = "RESET_COMMENT_EDIT_MODE";
export const SET_COMMENT_EDIT_MODE = "SET_COMMENT_EDIT_MODE";
export const EDIT_COMMENT_BEGIN = "EDIT_COMMENT_BEGIN";
export const EDIT_COMMENT_SUCCESS = "EDIT_COMMENT_SUCCESS";
export const EDIT_COMMENT_ERROR = "EDIT_COMMENT_ERROR";
